name: Build application
on: [push]
jobs:
  Build:
    runs-on: ubuntu-20.04
    container: node:16.13-buster
    steps:
      - uses: actions/checkout@v2
        with:
          path: frontend
      - run: npm ci