name: Build application
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-20.04
    container: node:16.13-buster
    steps:
      - uses: actions/checkout@v2
        with:
          path: frontend
      - name: "Build js"
        run: npm ci
        working-directory: frontend