name: Build application
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-20.04
    env:
      NODE_OPTIONS: "--max_old_space_size=1900"
    container:
      image: node:16.13-buster
    steps:
      - uses: actions/checkout@v2
      - name: "Install deps js"
        run: npm ci
      - name: "Build js"
        run: npm run build
      - name: "Copy to server"
        env:
          SSH_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          HOST: ${{ secrets.HOST }}
        run: |
          echo "$SSH_KEY" >> /tmp/ssh_key.rsa
          chmod 400 /tmp/ssh_key.rsa
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /tmp/ssh_key.rsa -r ./build/* root@$HOST:/var/www/app.agronomist.tech/
