name: Build application
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-20.04
    container: node:16.13-buster
    steps:
      - uses: actions/checkout@v2
        with:
          path: frontend
      - name: "Install deps js"
        run: npm ci
        working-directory: frontend
      - name: "Build js"
        run: npm run build
        working-directory: frontend
      - name: "test"
        run: "ls -la && ls -la frontend"
      - name: "Copy to server"
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HOST }}
          username: root
          privateKEy: ${{ secrets.SSH_DEPLOY_KEY }}
          local: "frontend/build/*"
          remote: "/var/www/app.agronomist.tech/"