name: Build application
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-20.04
    container:
      image: node:16.13-buster
    steps:
      - uses: actions/checkout@v2
      - name: "Install deps js"
        run: npm ci
      - name: "Build js"
        run: npm run build
      - name: "Copy to server"
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HOST }}
          username: root
          privateKey: ${{ secrets.SSH_DEPLOY_KEY }}
          local: "/__w/agrofrontend/agrofrontend/build/*"
          remote: "/var/www/app.agronomist.tech/"